# Generated by Django 2.2 on 2020-03-14 15:57

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topovske', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='category_en',
            field=models.CharField(choices=[('0', 'Pisma'), ('1', 'Spisak Žrtava'), ('2', 'Svedočenja'), ('3', 'Dokumenti'), ('4', 'Fotografije')], default='0', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='category_sr',
            field=models.CharField(choices=[('0', 'Pisma'), ('1', 'Spisak Žrtava'), ('2', 'Svedočenja'), ('3', 'Dokumenti'), ('4', 'Fotografije')], default='0', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='source_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='source_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='archive',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='text_sr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camp',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='image_text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='image_text_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='lead_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='lead_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='text_sr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='index',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='text_sr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='nationality_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='nationality_sr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
