# Generated by Django 2.2 on 2020-03-26 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topovske', '0002_auto_20200314_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='location',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='victim',
            name='source',
            field=models.CharField(blank=True, default=None, max_length=255),
        ),
    ]
