# Generated by Django 2.2 on 2020-04-19 16:46

from django.db import migrations
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('topovske', '0004_auto_20200419_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='location',
            field=location_field.models.plain.PlainLocationField(default='44.79688084502436,20.477120876312256', max_length=63),
        ),
    ]
