# Generated by Django 2.2 on 2020-04-26 18:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topovske', '0009_camphistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='camphistory',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='camphistory',
            name='text_sr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='camphistory',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camphistory',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='current',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='current',
            name='text_sr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='current',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='current',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publiccampaign',
            name='text_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='publiccampaign',
            name='text_sr',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='publiccampaign',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='publiccampaign',
            name='title_sr',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
