# Generated by Django 3.0.7 on 2020-07-21 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topovske', '0013_auto_20200721_1350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='source',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
