# Generated by Django 3.0.7 on 2020-07-22 13:08

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topovske', '0014_auto_20200721_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='camphistory',
            name='title_en',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='camphistory',
            name='text',
            field=ckeditor.fields.RichTextField(default=''),
        ),
    ]
