# Generated by Django 3.0.7 on 2020-07-24 22:15

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topovske', '0019_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
