# Generated by Django 3.0.7 on 2020-07-24 22:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topovske', '0021_auto_20200724_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, default=''),
        ),
    ]
