# Generated by Django 3.0.7 on 2020-07-24 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topovske', '0022_auto_20200724_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
